usr/include/

usr/lib/libdolphinprivate.so
usr/lib/libkdecorations.so
usr/lib/libkfontinst.so
usr/lib/libkfontinstui.so
usr/lib/libkickermain.so
usr/lib/libkonqsidebarplugin.so
usr/lib/libkscreensaver.so
usr/lib/libksgrd.so
usr/lib/libkwineffects.so
usr/lib/libkworkspace.so
usr/lib/libplasma.so
usr/lib/libprocesscore.so
usr/lib/libprocessui.so
usr/lib/libsolidcontrolifaces.so
usr/lib/libsolidcontrol.so
usr/lib/strigi/strigita_font.so

usr/share/kde4/apps/cmake
