usr/bin/kdepasswd
usr/lib/kde4/kcm_useraccount.so
usr/share/applications/kde4/kdepasswd.desktop
usr/share/doc/kde4/HTML/en/kdepasswd/common
usr/share/doc/kde4/HTML/en/kdepasswd/index.cache.bz2
usr/share/doc/kde4/HTML/en/kdepasswd/index.docbook
usr/share/doc/kde4/HTML/en/kdepasswd/password.png
usr/share/kde4/apps/kdm/pics/users/
usr/share/kde4/config.kcfg/kcm_useraccount.kcfg
usr/share/kde4/services/kcm_useraccount.desktop

