usr/share/icons/crystalsvg/48x48/apps/ksysguard.png
usr/share/icons/crystalsvg/32x32/apps/ksysguard.png
usr/share/icons/crystalsvg/16x16/apps/ksysguard.png
usr/share/icons/crystalsvg/128x128/apps/ksysguard.png
usr/share/icons/crystalsvg/64x64/apps/ksysguard.png
usr/lib/libkdeinit4_ksysguard.so
usr/bin/ksysguard
usr/share/applications/kde4/ksysguard.desktop
usr/share/kde4/apps/ksysguard/ProcessTable.sgrd
usr/share/kde4/apps/ksysguard/SystemLoad.sgrd
usr/share/kde4/apps/ksysguard/KSysGuardApplet.xml
usr/share/kde4/apps/ksysguard/default_theme.svg
usr/share/kde4/apps/ksysguard/ksysguardui.rc
usr/share/kde4/apps/kicker/applets/ksysguardapplet.desktop
usr/lib/libksgrd.so.4.0.0
usr/lib/libksgrd.so.4
usr/share/icons/crystalsvg/16x16/apps/waiting.png
usr/share/icons/crystalsvg/16x16/apps/computer.png
usr/share/icons/crystalsvg/16x16/apps/ksysguardd.png
usr/share/icons/oxygen/22x22/actions/view-process-system.png
usr/share/icons/crystalsvg/16x16/apps/kernel.png
usr/share/icons/crystalsvg/16x16/apps/shell.png
usr/share/icons/crystalsvg/16x16/apps/kdeapp.png
usr/share/icons/crystalsvg/16x16/apps/unknownapp.png
usr/share/icons/crystalsvg/16x16/apps/running.png
usr/share/icons/oxygen/16x16/actions/view-process-system.png
usr/share/icons/crystalsvg/16x16/apps/daemon.png
usr/share/kde4/apps/ksysguard/ksysguard.notifyrc
usr/lib/libprocesscore.so.4.0.0
usr/lib/libprocessui.so.4.0.0
usr/lib/kde4/plugins/designer/ksysguardwidgets.so
usr/lib/libprocesscore.so.4
usr/lib/libprocessui.so.4



usr/share/doc/kde4/HTML/en/ksysguard/index.cache.bz2
usr/share/doc/kde4/HTML/en/ksysguard/index.docbook
