
usr/lib/kde4/kded_favicons.so
usr/lib/kde4/konq_sound.so
usr/lib/libkonq.so.5
usr/lib/libkonq.so.5.0.0
usr/share/apps/kbookmark/directory_bookmarkbar.desktop
usr/share/apps/kconf_update/favicons.upd
usr/share/apps/kconf_update/move_favicons.sh
usr/share/apps/konqueror/pics/arrow_bottomleft.png
usr/share/apps/konqueror/pics/arrow_bottomright.png
usr/share/apps/konqueror/pics/arrow_topleft.png
usr/share/apps/konqueror/pics/arrow_topright.png
usr/share/apps/konqueror/pics/thumbnailfont_7x4.png
usr/share/dbus-1/interfaces/org.kde.FavIcon.xml
usr/share/dbus-1/interfaces/org.kde.libkonq.KonqHistoryManager.xml
usr/share/dbus-1/interfaces/org.kde.libkonq.UndoManager.xml
usr/share/kde4/services/kded/favicons.desktop
usr/share/kde4/servicetypes/konqpopupmenuplugin.desktop
